### ISSUE TITLE
[Sample Code] React Native Udemy course

### ISSUE THREAD

**Issue by andreidobrinski** [gdg-toronto/firebase-study-jam-season-1#2]
Here's a link to my [course code](https://github.com/andreidobrinski/react-native-course-udemy/tree/master) from a React Native implementation of some Firebase products.

The `auth` directory is a simple login/logout app that uses Firebase auth.

The `manager` directory uses Firebase auth as well as Realtime Database for a CRUD app.

Note that in `App.js`, I'm importing `firebaseConfig`. I put that file in my .gitignore but it's basically `export const firebaseConfig = { PASTE_CONFIG_HERE }`.

Hope it helps and let me know if you have any questions!

**Comment by SolomonHsu** [comment]
Interesting.

Thank you for sharing!
