### ISSUE TITLE
Firestore Rules for Authorized Content

### ISSUE THREAD

**Issue by markreale** [gdg-toronto/firebase-study-jam-season-1#9]
Running into an issue with setting up Firestore rules so that only content associated to a user can will be displayed to the user -

Here is the Data / Document structure:
```
thing: "help"
userId: "[generated_userid_string"
```

Here are the Firestore rules:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /things/{thing} {
    	allow read: if request.auth.uid == request.resource.data.userId;
      allow write: if request.auth.uid != null;
    }
  }
}
```

### Other notes:

- Auth is working fine
- Entries are successfully getting the correct uid associated to them
- the problem seems to be this line: ` allow read: if request.auth.uid == request.resource.data.userId; `
- I have also tried:
- ` allow read: if request.auth.uid == resource.data.userId; `
- ` allow read: if request.auth.uid == userId; `
- ` allow read: if request.auth.uid == $userId; `

Any thoughts on what is missing here?

Keep getting the result that Users do not have permissions to read any of the content even though it is being successfully associated to their userId -

Thanks!

**Comment by toddburgessmedia** [comment]
How about try:

match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
 }
match /things/{thing} {
    	allow read: if request.auth.uid == resource.data.userId;
}

**Comment by markreale** [comment]
Thanks for the suggestion!

Actually that ends up netting out at the same situation where every user has access to all user's entries and is not limited to only the entries associated with their userId

I think this part:
```
match /{document=**} {
allow read, write: if request.auth.uid != null;
}
```
allows users access to all content if they are logged in.

This part here:

```
match /things/{thing} {
allow read: if request.auth.uid == resource.data.userId;
  }
}
```
still seems to do nothing -

Let me know if any other thoughts come to mind!

Thanks -

**Comment by markreale** [comment]
Finally figured it out -

Looks like there was something wrong with my actual query and the original original Firestore rules were OK.

What an adventure.

**Comment by toddburgessmedia** [comment]
Welcome to Firebase :)
